services:
  osrm:
    image: osrm/osrm-backend:latest
    ports:
      - "5001:5000"
    volumes:
      - osrmdata:/data
    working_dir: /data
    command: >
      sh -c "
      if [ ! -f /data/new-york-latest.osrm ]; then
      sed -i '/stretch-updates/d' /etc/apt/sources.list && \
      sed -i 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' /etc/apt/sources.list && \
      sed -i 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' /etc/apt/sources.list && \
      apt-get update && \
      apt-get install -y wget && \
      rm -rf /var/lib/apt/lists/* && \
      wget -O /data/new-york-latest.osm.pbf http://download.geofabrik.de/north-america/us/new-york-latest.osm.pbf && \
      osrm-extract -p /opt/car.lua /data/new-york-latest.osm.pbf && \
      osrm-partition /data/new-york-latest.osrm && \
      osrm-customize /data/new-york-latest.osrm; \
      fi && \
      osrm-routed --algorithm mld /data/new-york-latest.osrm
      "

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"

volumes:
  pgdata:
  osrmdata:

